# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190215_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间'),
        ),
    ]
