# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间'),
        ),
    ]
